#live server configurations
##########################
#   RTMP configurations  #
##########################
[rtmp]
enabled = true
port = 1935
gop_num = 0
[rtmp.auth]
pull_enabled = false
push_enabled = false
# simple or md5
algorithm = "simple"

[[rtmp.push]]
enabled = false
address = "live-push.bilivideo.com"
port = 1936


[rtmp.bilibili]
enabled = true
server_addres = "rtmp://live-push.bilivideo.com/live-bvc/"
query = "?streamname=live_95060860_4349425&key=adde662293ff5d94b21cb344c0e47723&schedule=rtmp&pflag=1"


[httpnotify]
enabled = true
on_publish = "http://localhost:3001/on_publish"
on_unpublish = "http://localhost:3001/on_unpuslish"
on_play = "http://localhost:3001/on_play"
on_stop = "http://localhost:3001/on_stop"

[authsecret]
# used for md5 authentication
key = ""
# used for simple authentication
password = ""


##########################
#    RTSP configurations  #
##########################
[rtsp]
enabled = false
port = 445
[rtsp.auth]
pull_enabled = true
push_enabled = true
# simple or md5
algorithm = "simple"

##########################
#    WebRTC configurations  #
##########################
[webrtc]
enabled = false
port = 8083
[webrtc.auth]
pull_enabled = true
push_enabled = true
# simple or md5
algorithm = "simple"

##########################
# HTTPFLV configurations #
##########################
[httpflv]
enabled = false
port = 8081
[httpflv.auth]
pull_enabled = true
# simple or md5
algorithm = "simple"


##########################
#    HLS configurations  #
##########################
[hls]
enabled = false
port = 8080
need_record = false
[hls.auth]
pull_enabled = true
# simple or md5
algorithm = "simple"
